trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - agent.name -equals AgenteCloud

variables:
  azureServiceConnection: 'ServiciodeUsuariosyUbicaciones'
  azureWebAppName: 'ServiciodeUsuariosyUbicaciones'
  dockerRegistryServiceConnection: 'Contenedor_ServiciodeUsuariosyUbicaciones'
  imageRepository: 'serviciodeusuariosyubicaciones-app'
  containerRegistry: 'serviciodeusuariosyubicaciones.azurecr.io'
  tag: '$(Build.BuildId)'

steps:

- script: python --version
  displayName: 'Verificar versión de Python'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

# Listar archivos en la carpeta raíz
- script: |
    echo "Listando archivos en la raíz del repositorio:"
    dir
  displayName: 'Listar archivos en la raíz'

# Cambiar al directorio correcto y listar archivos
- script: |
    cd ServiciodeUsuariosyUbicaciones
    echo "Listando archivos en ServiciodeUsuariosyUbicaciones:"
    dir
    python -m venv virtual
    virtual\Scripts\activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias en entorno virtual'

- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)\ServiciodeUsuariosyUbicaciones\Dockerfile'
    buildContext: '$(Build.SourcesDirectory)\ServiciodeUsuariosyUbicaciones'
    tags: |
      $(tag)

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(azureWebAppName)'
    containers: |
      $(containerRegistry)/$(imageRepository):$(tag)